### ISSUE TITLE
Invalid Remote URL

### ISSUE THREAD

**Issue by moisesnqm** [alvr/ASFui#12]
Hi.
I'm trying to set-up ASFui with remote settings, but always show this message: Invalid Remote URL. I'm trying with net.tcp://myhost.ddns.net:1242/ASF and http://myhost.ddns.net:1242/ASF.
What am I doing wrong?

WCF is working fine.

**Comment by KlappPc** [comment]
Already fixed in the code, but not in the compiled version yet.
See: https://github.com/alvr/ASFui/pull/9

I have linked a compiled version somwhere in the SG thread, if you trust "third party" versions. Otherwise copile yourself or wait for alvr to publish new version.

PS: Basically ASF only works with net.tcp. But ASFui checks if the URL ist http: with someone listening, which can not work. Using old version of ASF would technically work, but I am not sure, if that is worth it.

**Comment by CrazyEstrellita** [comment]
Still not working
net.tcp://127.0.0.1:1242/ASF

But if it does not work on the same PC, let alone on another PC in LAN
Meanwhile it will be for steam chat ㋡

**Comment by KlappPc** [comment]
What is not working?
The check for a valid URL or the WCF stuff itself?

Try to issue a command using the ASF.exe as client (as described in the ASF wiki for WCF). If that works, but ASFui does not, reply again.
If that does not work as well, your WCF configuration is faulty.
